# Generated by Django 5.0.14 on 2026-01-11 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecommerce',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(help_text='Secret API Key used for backend-to-backend communication', max_length=255, unique=True)),
                ('public_key', models.CharField(help_text='Public Key used in the frontend widget', max_length=255, unique=True)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='The public voucher ID entered by the shopper', max_length=50, unique=True)),
                ('security_code', models.CharField(help_text='The secret code entered by the shopper', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='fixed', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voucher_code', models.CharField(blank=True, max_length=50, null=True)),
                ('voucher_secret', models.CharField(blank=True, max_length=50, null=True)),
                ('ecommerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.ecommerce')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseVoucher',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_vouchers', to='api.purchase')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.voucher')),
            ],
            options={
                'unique_together': {('purchase', 'voucher')},
            },
        ),
    ]
